---
abstract: 'Instantiate Moose classes with failover'
author:
  - 'Robert Rothenberg <rrwo@thermeon.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooseX-Failover
recommends:
  Class::Load::XS: '0'
  PerlX::Maybe::XS: '0'
requires:
  Carp: '0'
  Class::Load: '0.20'
  Moose: '2.1101'
  PerlX::Maybe: '0.03'
  Test::Most: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/robrwo/MooseX-Failover/issues
  repository: git://github.com/robrwo/MooseX-Failover.git
version: v0.1.1
